# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datetime.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selectDateTime(object):
    def setupUi(self, selectDateTime):
        selectDateTime.setObjectName("selectDateTime")
        selectDateTime.setWindowModality(QtCore.Qt.WindowModal)
        selectDateTime.resize(341, 144)
        self.okButton = QtWidgets.QPushButton(selectDateTime)
        self.okButton.setGeometry(QtCore.QRect(70, 100, 75, 23))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(selectDateTime)
        self.cancelButton.setGeometry(QtCore.QRect(190, 100, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(selectDateTime)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 0, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.timeEdit = QtWidgets.QTimeEdit(self.verticalLayoutWidget)
        self.timeEdit.setDate(QtCore.QDate(2000, 1, 17))
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout.addWidget(self.timeEdit)

        self.retranslateUi(selectDateTime)
        QtCore.QMetaObject.connectSlotsByName(selectDateTime)

    def retranslateUi(self, selectDateTime):
        _translate = QtCore.QCoreApplication.translate
        selectDateTime.setWindowTitle(_translate("selectDateTime", "Select date and time"))
        self.okButton.setText(_translate("selectDateTime", "Ок"))
        self.cancelButton.setText(_translate("selectDateTime", "Отмена"))
