# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Report_Form(object):
    def setupUi(self, Report_Form):
        Report_Form.setObjectName("Report_Form")
        Report_Form.resize(522, 183)
        Report_Form.setStyleSheet("QLabel {background-color: none}")
        self.label_Title = QtWidgets.QLabel(Report_Form)
        self.label_Title.setGeometry(QtCore.QRect(60, 20, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Title.setFont(font)
        self.label_Title.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title.setObjectName("label_Title")
        self.label_From = QtWidgets.QLabel(Report_Form)
        self.label_From.setGeometry(QtCore.QRect(50, 85, 21, 31))
        self.label_From.setObjectName("label_From")
        self.label_To = QtWidgets.QLabel(Report_Form)
        self.label_To.setGeometry(QtCore.QRect(300, 80, 21, 39))
        self.label_To.setObjectName("label_To")
        self.reportButton_graph = QtWidgets.QPushButton(Report_Form)
        self.reportButton_graph.setGeometry(QtCore.QRect(190, 140, 131, 23))
        self.reportButton_graph.setObjectName("reportButton_graph")
        self.fromDateButton = QtWidgets.QPushButton(Report_Form)
        self.fromDateButton.setGeometry(QtCore.QRect(70, 90, 181, 23))
        self.fromDateButton.setObjectName("fromDateButton")
        self.toDateButton = QtWidgets.QPushButton(Report_Form)
        self.toDateButton.setGeometry(QtCore.QRect(330, 90, 181, 23))
        self.toDateButton.setObjectName("toDateButton")

        self.retranslateUi(Report_Form)
        QtCore.QMetaObject.connectSlotsByName(Report_Form)

    def retranslateUi(self, Report_Form):
        _translate = QtCore.QCoreApplication.translate
        Report_Form.setWindowTitle(_translate("Report_Form", "Создать график"))
        self.label_Title.setText(_translate("Report_Form", "Выберите период времени"))
        self.label_From.setText(_translate("Report_Form", "С:"))
        self.label_To.setText(_translate("Report_Form", "По:"))
        self.reportButton_graph.setText(_translate("Report_Form", "Ок"))
        self.fromDateButton.setText(_translate("Report_Form", "Дата начала отчёта"))
        self.toDateButton.setText(_translate("Report_Form", "Дата окончания отчёта"))
